name: Docker Lifecycle

# login to your private registry, build & push image, and then delete image from your runner
# this is for monorepo project 

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      DOCKER_REGISTRY_NAME:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
      PROJECT_DIRECTORY:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY_USERNAME:
        description: 'Your Private Registry Username'
        required: true
      DOCKER_REGISTRY_PASSWORD:
        description: 'Your Private Registry Password'
        required: true
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Login Docker 
      - name: login to ${{ inputs.DOCKER_REGISTRY_NAME }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.DOCKER_REGISTRY_NAME }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}   

      # Docker Image Meta Data
      - name: ${{ inputs.PROJECT_DIRECTORY }} docker image meta data
        id: meta_${{ inputs.PROJECT_DIRECTORY }}
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.DOCKER_REGISTRY_NAME }}/${{ inputs.PROJECT_NAME}}/${{ inputs.PROJECT_DIRECTORY }}
          tags: type=raw,value=latest,enable={{is_default_branch}} 
      
      # Build and Push Docker Image
      - name: build and push docker image ${{ inputs.PROJECT_DIRECTORY }}
        uses: docker/build-push-action@v3
        with:
          context: ./${{ inputs.PROJECT_DIRECTORY }}
          push: true
          tags: ${{ format('steps.meta_{0}.outputs.tags', inputs.PROJECT_DIRECTORY )}}
          labels: ${{ format('steps.meta_{0}.outputs.labels', inputs.PROJECT_DIRECTORY )}}
        
      # Delete Docker Image
      - name: Delete docker images ${{ inputs.PROJECT_DIRECTORY }} after build & push
        run: |
          docker rmi ${{ format('steps.meta_{0}.outputs.tags', inputs.PROJECT_DIRECTORY )}}
          docker system prune --force